#!/bin/sh
set -euo pipefail

# create s3 bucket to hold zipped lambdas
#aws s3 mb s3://yargevad-spevents-lambdas

aws cloudformation package \
  --template-file event-data.yaml \
  --output-template-file event-data.cf.yaml \
  --s3-bucket yargevad-spevents-lambdas
  
